name: Sync CI
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  test:
    name: Run action
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: ./
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          SLACK_BOT_ACCESS_TOKEN: ${{ secrets.SLACK_BOT_ACCESS_TOKEN }}
