name: Sync CI
on:
  workflow_dispatch:
jobs:
  test:
    name: Run action
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, 'Deploy new version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: ./
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          SLACK_BOT_ACCESS_TOKEN: ${{ secrets.SLACK_BOT_ACCESS_TOKEN }}
